package com.aiu.tdminsight.features.export

import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * SummaryExporter.kt
 * Owner: Benat
 *
 * Exports a patient case's result summary as a plain text file and
 * launches the Android share sheet so the user can send it via email,
 * messaging apps, save to Drive, etc.
 *
 * DEPENDENCY (flagged for Yalda): this relies on a FileProvider, which
 * must be declared in AndroidManifest.xml, plus a matching
 * res/xml/file_paths.xml (included alongside this file). Until that
 * manifest entry exists, export will fail at runtime with a
 * FileUriExposedException — but the code itself is complete and will
 * work as soon as the manifest entry is added. See the AndroidManifest
 * snippet in the project docs / PR description for the exact XML to add.
 *
 * Manifest entry needed (inside <application> ... </application>):
 *
 * <provider
 *     android:name="androidx.core.content.FileProvider"
 *     android:authorities="${applicationId}.fileprovider"
 *     android:exported="false"
 *     android:grantUriPermissions="true">
 *     <meta-data
 *         android:name="android.support.FILE_PROVIDER_PATHS"
 *         android:resource="@xml/file_paths" />
 * </provider>
 */

/**
 * The data needed to build a shareable summary. Kept as a simple,
 * self-contained model here (rather than depending directly on
 * PatientCaseFormState or TdmResult) so this file has no compile-time
 * dependency on other people's in-progress files. Map from the real
 * models to this at the call site once they're finalized.
 */
data class ExportableSummary(
    val patientId: String,
    val patientName: String?,
    val dateLabel: String,
    val levelType: String,
    val measuredLevel: String,
    val recommendation: String,
    val notes: String? = null
)

object SummaryExporter {

    /**
     * Builds the plain-text content of the summary file.
     * Separated from the file-writing logic so it can be unit tested
     * without touching the filesystem.
     */
    fun buildSummaryText(summary: ExportableSummary): String {
        val builder = StringBuilder()
        builder.appendLine("TDM Insight — Case Summary")
        builder.appendLine("Generated: ${currentTimestamp()}")
        builder.appendLine()
        builder.appendLine("Patient ID: ${summary.patientId}")
        summary.patientName?.let { builder.appendLine("Patient Name: $it") }
        builder.appendLine("Case Date: ${summary.dateLabel}")
        builder.appendLine()
        builder.appendLine("Level Type: ${summary.levelType}")
        builder.appendLine("Measured Level: ${summary.measuredLevel} mg/L")
        builder.appendLine()
        builder.appendLine("Recommendation: ${summary.recommendation}")
        summary.notes?.let {
            builder.appendLine()
            builder.appendLine("Notes: $it")
        }
        builder.appendLine()
        builder.appendLine("— Generated by TDM Insight. For clinical decision support only.")
        return builder.toString()
    }

    /**
     * Writes the summary to a file in the app's cache directory and
     * launches the Android share sheet so the user can send it wherever
     * they like.
     *
     * @param context an Activity or Application context
     * @param summary the case data to export
     */
    fun exportAndShare(context: Context, summary: ExportableSummary) {
        val fileName = "tdm_summary_${summary.patientId}_${System.currentTimeMillis()}.txt"
        val exportDir = File(context.cacheDir, "exports").apply { mkdirs() }
        val file = File(exportDir, fileName)

        FileWriter(file).use { writer ->
            writer.write(buildSummaryText(summary))
        }

        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )

        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, "TDM Insight Case Summary — ${summary.patientId}")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }

        context.startActivity(
            Intent.createChooser(shareIntent, "Share case summary")
        )
    }

    private fun currentTimestamp(): String {
        val formatter = SimpleDateFormat("dd MMM yyyy, HH:mm", Locale.getDefault())
        return formatter.format(Date())
    }
}